CREATE OR REPLACE CORTEX SEARCH SERVICE SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.HANDSON_DOCS_SEARCH
  ON CONTENT
  ATTRIBUTES TITLE, DOCUMENT_TYPE, DEPARTMENT
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
  AS (
    SELECT
      CONTENT,
      TITLE,
      DOCUMENT_TYPE,
      DEPARTMENT,
      DOCUMENT_ID
    FROM SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.SNOW_RETAIL_DOCUMENTS
  );
