-- Cortex Search Service: HANDSON_DOCS_SEARCH
-- Database : SNOWRETAIL_DB
-- Schema   : SNOWRETAIL_SCHEMA
-- Source   : SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.SNOW_RETAIL_DOCUMENTS
-- Created  : 2026-05-11

CREATE OR REPLACE CORTEX SEARCH SERVICE SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.HANDSON_DOCS_SEARCH
  ON CONTENT
  ATTRIBUTES DOCUMENT_ID, TITLE, DOCUMENT_TYPE, DEPARTMENT, VERSION, CREATED_AT
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 day'
  REFRESH_MODE = INCREMENTAL
AS
  SELECT
    DOCUMENT_ID,
    TITLE,
    CONTENT,
    DOCUMENT_TYPE,
    DEPARTMENT,
    VERSION,
    CREATED_AT
  FROM SNOWRETAIL_DB.SNOWRETAIL_SCHEMA.SNOW_RETAIL_DOCUMENTS;
